<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.  ['id' => 3, 'name' => 'permission_3', 'guard_name' =>'guard_name' => 'web', 'created_at' => '2023-10-14 09:21:03', 'updated_at' => '2023-10-14 11:02:56'],
           
     */
    public function run(): void
    {
        $permissions = [
            ['id' => 3, 'name' => 'roles.index', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 4, 'name' => 'roles.create', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 5, 'name' => 'roles.store', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 6, 'name' => 'roles.show', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 7, 'name' => 'roles.edit', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 8, 'name' => 'roles.update', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 9, 'name' => 'roles.destroy', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 10, 'name' => 'permissions.index', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 11, 'name' => 'permissions.create', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 12, 'name' => 'permissions.store', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 13, 'name' => 'permissions.show', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 14, 'name' => 'permissions.edit', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 15, 'name' => 'permissions.update', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 16, 'name' => 'permissions.destroy', 'guard_name' => 'web', 'group_name' => 'permissions'],
            ['id' => 17, 'name' => 'dashboard', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 18, 'name' => 'profile.edit', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 19, 'name' => 'profile.update', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 20, 'name' => 'profile.destroy', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 21, 'name' => 'cardcheck', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 22, 'name' => 'getcardinfo', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 23, 'name' => 'category.index', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 24, 'name' => 'category.create', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 25, 'name' => 'category.store', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 26, 'name' => 'category.show', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 27, 'name' => 'category.edit', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 28, 'name' => 'category.update', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 29, 'name' => 'category.destroy', 'guard_name' => 'web', 'group_name' => 'category'],
            ['id' => 30, 'name' => 'subcategory.index', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 31, 'name' => 'subcategory.create', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 32, 'name' => 'subcategory.store', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 33, 'name' => 'subcategory.show', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 34, 'name' => 'subcategory.edit', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 35, 'name' => 'subcategory.update', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 36, 'name' => 'subcategory.destroy', 'guard_name' => 'web', 'group_name' => 'subcategory'],
            ['id' => 37, 'name' => 'menus.index', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 38, 'name' => 'menus.create', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 39, 'name' => 'menus.store', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 40, 'name' => 'menus.show', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 41, 'name' => 'menus.edit', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 42, 'name' => 'menus.update', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 43, 'name' => 'menus.destroy', 'guard_name' => 'web', 'group_name' => 'menus'],
            ['id' => 44, 'name' => 'tab.index', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 45, 'name' => 'tab.create', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 46, 'name' => 'tab.store', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 47, 'name' => 'tab.show', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 48, 'name' => 'tab.edit', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 49, 'name' => 'tab.update', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 50, 'name' => 'tab.destroy', 'guard_name' => 'web', 'group_name' => 'tab'],
            ['id' => 51, 'name' => 'offorder.index', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 52, 'name' => 'offorder.create', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 53, 'name' => 'offorder.store', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 54, 'name' => 'offorder.show', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 55, 'name' => 'offorder.edit', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 56, 'name' => 'offorder.update', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 57, 'name' => 'offorder.destroy', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 58, 'name' => 'setting.index', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 59, 'name' => 'setting.create', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 60, 'name' => 'setting.store', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 61, 'name' => 'setting.show', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 62, 'name' => 'setting.edit', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 63, 'name' => 'setting.update', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 64, 'name' => 'setting.destroy', 'guard_name' => 'web', 'group_name' => 'setting'],
            ['id' => 65, 'name' => 'offorderdetails.index', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 66, 'name' => 'offorderdetails.create', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 67, 'name' => 'offorderdetails.store', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 68, 'name' => 'offorderdetails.show', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 69, 'name' => 'offorderdetails.edit', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 70, 'name' => 'offorderdetails.update', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 71, 'name' => 'offorderdetails.destroy', 'guard_name' => 'web', 'group_name' => 'offorderdetails'],
            ['id' => 72, 'name' => 'supplier.index', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 73, 'name' => 'supplier.create', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 74, 'name' => 'supplier.store', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 75, 'name' => 'supplier.show', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 76, 'name' => 'supplier.edit', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 77, 'name' => 'supplier.update', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 78, 'name' => 'supplier.destroy', 'guard_name' => 'web', 'group_name' => 'supplier'],
            ['id' => 79, 'name' => 'material.index', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 80, 'name' => 'material.create', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 81, 'name' => 'material.store', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 82, 'name' => 'material.show', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 83, 'name' => 'material.edit', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 84, 'name' => 'material.update', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 85, 'name' => 'material.destroy', 'guard_name' => 'web', 'group_name' => 'material'],
            ['id' => 86, 'name' => 'purchase.index', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 87, 'name' => 'purchase.create', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 88, 'name' => 'purchase.store', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 89, 'name' => 'purchase.show', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 90, 'name' => 'purchase.edit', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 91, 'name' => 'purchase.update', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 92, 'name' => 'purchase.destroy', 'guard_name' => 'web', 'group_name' => 'purchase'],
            ['id' => 93, 'name' => 'role.index', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 94, 'name' => 'role.create', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 95, 'name' => 'role.store', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 96, 'name' => 'role.show', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 97, 'name' => 'role.edit', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 98, 'name' => 'role.update', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 99, 'name' => 'role.destroy', 'guard_name' => 'web', 'group_name' => 'role'],
            ['id' => 100, 'name' => 'urole.index', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 101, 'name' => 'urole.create', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 102, 'name' => 'urole.store', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 103, 'name' => 'urole.show', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 104, 'name' => 'urole.edit', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 105, 'name' => 'urole.update', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 106, 'name' => 'urole.destroy', 'guard_name' => 'web', 'group_name' => 'urole'],
            ['id' => 107, 'name' => 'card.index', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 108, 'name' => 'card.create', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 109, 'name' => 'card.store', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 110, 'name' => 'card.show', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 111, 'name' => 'card.edit', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 112, 'name' => 'card.update', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 113, 'name' => 'card.destroy', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 114, 'name' => 'cardp.index', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 115, 'name' => 'cardp.create', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 116, 'name' => 'cardp.store', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 117, 'name' => 'cardp.show', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 118, 'name' => 'cardp.edit', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 119, 'name' => 'cardp.update', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 120, 'name' => 'cardp.destroy', 'guard_name' => 'web', 'group_name' => 'card'],
            ['id' => 121, 'name' => 'customer.index', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 122, 'name' => 'customer.create', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 123, 'name' => 'customer.store', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 124, 'name' => 'customer.show', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 125, 'name' => 'customer.edit', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 126, 'name' => 'customer.update', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 127, 'name' => 'customer.destroy', 'guard_name' => 'web', 'group_name' => 'customer'],
            ['id' => 128, 'name' => 'register', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 129, 'name' => 'login', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 130, 'name' => 'password.request', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 131, 'name' => 'password.email', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 132, 'name' => 'password.reset', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 133, 'name' => 'password.store', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 134, 'name' => 'verification.notice', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 135, 'name' => 'verification.verify', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 136, 'name' => 'verification.send', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 137, 'name' => 'password.confirm', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 138, 'name' => 'password.update', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 139, 'name' => 'logout', 'guard_name' => 'web', 'group_name' => 'web'],
            ['id' => 140, 'name' => 'offorderdaily', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 141, 'name' => 'users.index', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 142, 'name' => 'users.create', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 143, 'name' => 'users.store', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 144, 'name' => 'users.show', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 145, 'name' => 'users.edit', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 146, 'name' => 'users.update', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 147, 'name' => 'users.destroy', 'guard_name' => 'web', 'group_name' => 'users'],
            ['id' => 148, 'name' => 'catorder', 'guard_name' => 'web', 'group_name' =>''],
            ['id' => 149, 'name' => 'dailyreport', 'guard_name' => 'web', 'group_name' =>''],
            ['id' => 150, 'name' => 'order', 'guard_name' => 'web', 'group_name' =>''],
            ['id' => 151, 'name' => 'offorderlog', 'guard_name' => 'web', 'group_name' => 'offorder'],
            ['id' => 152, 'name' => 'menulog', 'guard_name' => 'web', 'group_name' =>''],
            ['id' => 153, 'name' => 'sanctum.csrf-cookie', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 154, 'name' => 'admins.index', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 155, 'name' => 'admins.create', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 156, 'name' => 'admins.store', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 157, 'name' => 'admins.show', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 158, 'name' => 'admins.edit', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 159, 'name' => 'admins.update', 'guard_name' => 'web', 'group_name' =>'',],
            ['id' => 160, 'name' => 'admins.destroy', 'guard_name' => 'web', 'group_name' =>'',],
        ];

        // Insert data into the'group_name' => 'permissions' table
        DB::table('permissions')->insert($permissions);
    }
}
